//! Bloom filter serialization using rkyv
//!
//! The `bloomfilter` crate only supports serde, so we create a custom
//! rkyv-serializable wrapper that can convert to/from `Bloom<T>`.

use bloomfilter::Bloom;
use era_common::{ChunkHash, EraError, Result};
use rkyv::{Archive, Deserialize as RkyvDeserialize, Serialize as RkyvSerialize};
use std::hash::Hash;

/// V25-F2 fix: consolidate MAX_BLOOM_BITMAP_SIZE to single module-level definition.
/// Maximum allowed bloom bitmap size in bytes (128 MiB). Used by both
/// `from_bytes()` and `validate_archived()` to reject oversized bitmaps.
const MAX_BLOOM_BITMAP_SIZE: usize = 128 * 1024 * 1024;

/// Serializable representation of a Bloom filter
///
/// This struct captures the essential state of a `Bloom<T>` filter
/// in a format that can be serialized with rkyv.
///
/// V23-F1 fix: Fields are `pub(crate)` to prevent external consumers from
/// bypassing the validated `new()` constructor via struct literal construction.
/// Use `new()` or `from_bytes()` to create instances.
#[derive(Archive, RkyvDeserialize, RkyvSerialize, Debug, Clone)]
#[archive(check_bytes)]
pub struct BloomFilterData {
    /// Schema version for future evolution (currently 1)
    pub(crate) version: u8,
    /// The bit vector as raw bytes
    pub(crate) bitmap: Vec<u8>,
    /// Number of bits in the filter
    pub(crate) bitmap_bits: u64,
    /// Number of hash functions (k)
    pub(crate) k_num: u32,
    /// SipHasher keys for reproducible hashing, randomly generated by the
    /// `bloomfilter` crate. Not a security primitive — adversarial knowledge
    /// only causes false positives, never data loss. Full hash comparison is
    /// the authoritative dedup check.
    pub(crate) sip_keys: [(u64, u64); 2],
}

impl BloomFilterData {
    /// V23-F3 fix: Consolidated validation for bloom filter parameters.
    ///
    /// Checks that bitmap_bits > 0, k_num > 0, bitmap is large enough
    /// for bitmap_bits, and sip_keys are not all zeros. Called by `new()`,
    /// `from_bloom()`, `to_bloom()`, and `from_bytes()` to enforce invariants
    /// at every construction and conversion boundary.
    fn validate(&self) -> Result<()> {
        if self.bitmap_bits == 0 {
            return Err(EraError::IndexError(
                "BloomFilterData: bitmap_bits is 0".into(),
            ));
        }
        if self.k_num == 0 {
            return Err(EraError::IndexError("BloomFilterData: k_num is 0".into()));
        }
        if (self.bitmap.len() as u64) * 8 < self.bitmap_bits {
            return Err(EraError::IndexError(format!(
                "BloomFilterData: bitmap too short: {} bytes for {} bits",
                self.bitmap.len(),
                self.bitmap_bits
            )));
        }
        if self.sip_keys == [(0, 0); 2] {
            return Err(EraError::IndexError(
                "BloomFilterData: sip_keys are all zeros".into(),
            ));
        }
        // V24-F9 fix: Reject degenerate SipHash keys where both pairs are identical.
        // Identical keys reduce the effective hash function count, degrading bloom accuracy.
        if self.sip_keys[0] == self.sip_keys[1] {
            return Err(EraError::IndexError(
                "BloomFilterData: sip_keys are degenerate (both pairs identical)".into(),
            ));
        }
        Ok(())
    }

    // V22-F5 fix: Validated constructor for BloomFilterData.
    // Previously, the only way to create a BloomFilterData was via `from_bloom()`
    // or direct struct literal construction (since all fields were pub).
    // This constructor validates invariants upfront, catching invalid parameters
    // before they reach `to_bloom()` or `to_bytes()`.
    /// Create a validated BloomFilterData with parameter checks.
    ///
    /// Returns an error if bitmap_bits is 0, k_num is 0, bitmap is too short
    /// for the specified bitmap_bits, or sip_keys are all zeros.
    pub fn new(
        bitmap: Vec<u8>,
        bitmap_bits: u64,
        k_num: u32,
        sip_keys: [(u64, u64); 2],
    ) -> Result<Self> {
        let data = Self {
            version: 1,
            bitmap,
            bitmap_bits,
            k_num,
            sip_keys,
        };
        // V23-F3 fix: Delegate to consolidated validate() method.
        data.validate()?;
        Ok(data)
    }

    /// Accessor for the schema version.
    #[must_use]
    pub fn version(&self) -> u8 {
        self.version
    }

    /// Accessor for the raw bitmap bytes.
    #[must_use]
    pub fn bitmap_ref(&self) -> &[u8] {
        &self.bitmap
    }

    /// Accessor for the number of bits in the filter.
    #[must_use]
    pub fn bitmap_bits(&self) -> u64 {
        self.bitmap_bits
    }

    /// Accessor for the number of hash functions (k).
    #[must_use]
    pub fn k_num(&self) -> u32 {
        self.k_num
    }

    /// Accessor for the SipHasher keys.
    #[must_use]
    pub fn sip_keys(&self) -> [(u64, u64); 2] {
        self.sip_keys
    }

    /// Create from a Bloom filter.
    ///
    /// V23-F2 fix: Now validates the extracted parameters via `validate()`.
    /// V23-F5 fix: Restricted to `pub(crate)` — only used within the crate
    /// by `serialize_bloom()`.
    pub(crate) fn from_bloom<T: Hash>(bloom: &Bloom<T>) -> Result<Self> {
        // Get the internal bitmap as bytes
        let bitmap = bloom.bitmap();
        let bitmap_bits = bloom.number_of_bits();
        let k_num = bloom.number_of_hash_functions();
        let sip_keys = bloom.sip_keys();

        let data = Self {
            version: 1,
            bitmap,
            bitmap_bits,
            k_num,
            sip_keys,
        };
        data.validate()?;
        Ok(data)
    }

    /// V21-F4 fix: Convert back to a Bloom filter with validation.
    ///
    /// Validates parameters before constructing the bloom filter to prevent
    /// panics from invalid state.
    pub fn to_bloom<T: Hash>(&self) -> Result<Bloom<T>> {
        // V23-F3 fix: Delegate to consolidated validate() method.
        self.validate()?;
        Ok(Bloom::from_existing(
            &self.bitmap,
            self.bitmap_bits,
            self.k_num,
            self.sip_keys,
        ))
    }

    /// Serialize to bytes using rkyv.
    ///
    /// V23-F4 fix: `.to_vec()` copies the `rkyv::AlignedVec` into a standard
    /// `Vec<u8>`. This copy is necessary because `AlignedVec` uses a different
    /// allocator alignment and does not implement `Into<Vec<u8>>`.
    pub fn to_bytes(&self) -> Result<Vec<u8>> {
        rkyv::to_bytes::<_, 4096>(self)
            .map(|bytes| bytes.to_vec())
            .map_err(|e| EraError::Serialization(e.to_string()))
    }

    /// Deserialize from bytes using rkyv (check_archived_root + deserialize).
    ///
    /// V17-F9 fix: Validates the schema version on the archived (zero-copy) view
    /// BEFORE performing the full deserialization to avoid allocating the bitmap
    /// Vec for unsupported versions.
    pub fn from_bytes(bytes: &[u8]) -> Result<Self> {
        let archived = rkyv::check_archived_root::<Self>(bytes)
            .map_err(|e| EraError::Deserialization(e.to_string()))?;
        // V17-F9: Version check.
        if archived.version != 1 {
            return Err(EraError::IndexError(format!(
                "unsupported bloom filter version: {}",
                archived.version
            )));
        }
        // V24-F8: Pre-deser bitmap check.
        Self::validate_archived(archived)?;
        let result: Self = match archived.deserialize(&mut rkyv::Infallible) {
            Ok(val) => val,
            Err(never) => match never {},
        };
        result.validate()?;
        // V19-F4 fix: Reject oversized bloom bitmaps that could exhaust memory.
        // 128 MiB is generous for any realistic bloom filter.
        // (defense-in-depth: pre-deserialize check above is the primary guard)
        if result.bitmap.len() > MAX_BLOOM_BITMAP_SIZE {
            return Err(EraError::IndexError(format!(
                "bloom filter bitmap too large: {} bytes (max {})",
                result.bitmap.len(),
                MAX_BLOOM_BITMAP_SIZE
            )));
        }
        Ok(result)
    }

    /// V24-F8: Pre-deserialize size validation on archived (zero-copy) view.
    /// Checks bitmap size, bitmap length consistency, and bitmap_bits bounds.
    fn validate_archived(archived: &ArchivedBloomFilterData) -> Result<()> {
        if archived.bitmap.len() > MAX_BLOOM_BITMAP_SIZE {
            return Err(EraError::IndexError(format!(
                "bloom bitmap too large (pre-deser): {} B (max {})",
                archived.bitmap.len(),
                MAX_BLOOM_BITMAP_SIZE
            )));
        }
        if (archived.bitmap.len() as u64) * 8 < archived.bitmap_bits {
            return Err(EraError::IndexError(format!(
                "bloom bitmap too short (pre-deser): {} B for {} bits",
                archived.bitmap.len(),
                archived.bitmap_bits
            )));
        }
        let max_bits = (MAX_BLOOM_BITMAP_SIZE as u64) * 8;
        if archived.bitmap_bits > max_bits {
            return Err(EraError::IndexError(format!(
                "bloom bitmap_bits too large (pre-deser): {} (max {})",
                archived.bitmap_bits, max_bits
            )));
        }
        Ok(())
    }
}

/// Serialize a Bloom<ChunkHash> to bytes
pub fn serialize_bloom(bloom: &Bloom<ChunkHash>) -> Result<Vec<u8>> {
    BloomFilterData::from_bloom(bloom)?.to_bytes()
}

/// Deserialize a Bloom<ChunkHash> from bytes
pub fn deserialize_bloom(bytes: &[u8]) -> Result<Bloom<ChunkHash>> {
    BloomFilterData::from_bytes(bytes)?.to_bloom()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_hash(value: u64) -> ChunkHash {
        let mut bytes = [0u8; 32];
        bytes[24..32].copy_from_slice(&value.to_be_bytes());
        ChunkHash::from_bytes(bytes)
    }

    #[test]
    fn test_bloom_roundtrip() {
        let mut bloom: Bloom<ChunkHash> = Bloom::new_for_fp_rate(1000, 0.01);

        // Insert some hashes
        for i in 0..100 {
            bloom.set(&test_hash(i));
        }

        // Serialize
        let bytes = serialize_bloom(&bloom).unwrap();

        // Deserialize
        let restored = deserialize_bloom(&bytes).unwrap();

        // Verify all inserted hashes are found
        for i in 0..100 {
            assert!(restored.check(&test_hash(i)), "Hash {} not found", i);
        }

        // Verify non-inserted hashes are mostly not found (allowing for FP rate)
        let mut false_positives = 0;
        for i in 100..200 {
            if restored.check(&test_hash(i)) {
                false_positives += 1;
            }
        }
        // Should be < 5% false positives (we set 1% FP rate)
        assert!(
            false_positives < 5,
            "Too many false positives: {}",
            false_positives
        );
    }

    #[test]
    fn test_bloom_data_serialization() {
        let bloom: Bloom<ChunkHash> = Bloom::new_for_fp_rate(100, 0.01);
        let data = BloomFilterData::from_bloom(&bloom).unwrap();

        let bytes = data.to_bytes().unwrap();
        let restored = BloomFilterData::from_bytes(&bytes).unwrap();

        assert_eq!(data.version, restored.version);
        assert_eq!(data.bitmap_bits, restored.bitmap_bits);
        assert_eq!(data.k_num, restored.k_num);
        assert_eq!(data.sip_keys, restored.sip_keys);
        assert_eq!(data.bitmap, restored.bitmap);
    }

    #[test]
    fn test_bloom_version_validation() {
        // Create a valid BloomFilterData
        let bloom: Bloom<ChunkHash> = Bloom::new_for_fp_rate(100, 0.01);
        let mut data = BloomFilterData::from_bloom(&bloom).unwrap();

        // Serialize with version 1
        let bytes = data.to_bytes().unwrap();

        // Verify it deserializes successfully
        let result = BloomFilterData::from_bytes(&bytes);
        assert!(result.is_ok());

        // Now create invalid data with version 2
        // V23-F1 fix: Fields are pub(crate), so this mutation is still valid
        // within the crate's test module.
        data.version = 2;
        let bytes = data.to_bytes().unwrap();

        // Verify deserialization rejects version 2
        let result = BloomFilterData::from_bytes(&bytes);
        assert!(result.is_err());
        if let Err(e) = result {
            let err_msg = e.to_string();
            assert!(
                err_msg.contains("unsupported bloom filter version"),
                "Expected version error, got: {}",
                err_msg
            );
        }
    }
}
